### ISSUE TITLE
Implement addRide service

### ISSUE THREAD

**Issue by shriramsharma** [VoluteeRide/VolunteeRideApp-svc#5] opened 2015-08-14 19:50 UTC
#### Acceptance criteria:
- Should receive POST calls on the service.
- Persist in DB
- Write unit test
- Write functional test

**Comment by ayazlakdawala** [comment] 2015-09-04 02:16
Closing this issue as this is a duplicate of #7

**Closed as completed by ayazlakdawala** 2015-09-04 02:16 UTC
Labels: duplicate
