### ISSUE TITLE
Create basic service project structure.

### ISSUE THREAD

**Issue by shriramsharma** [VoluteeRide/VolunteeRideApp-svc#3] opened 2015-08-04 05:45 UTC
Acceptance criteria
1. Create project structure using gradle/maven.
2. Should have a service interface with GET/POST/PUT/DELETE APIs
3. Should be deployable on apache tomcat.

**Comment by ayazlakdawala** [comment] 2015-09-04 02:15
Closing this issue as this is a duplicate of #6

**Closed as completed by ayazlakdawala** 2015-09-04 02:15 UTC
Labels: duplicate
